/* Generated by tools/build.js. Lets the site work offline and picks up new questions
   automatically. The version changes whenever any page, script, style or data file changes. */
const VERSION = "0c6f3a6697f4";
const CACHE = "certhub-" + VERSION;
const PRECACHE = [
  "/",
  "/404.html",
  "/assets/app.js",
  "/assets/core.js",
  "/assets/engine.js",
  "/assets/fonts/public-sans-latin-400-normal.woff2",
  "/assets/fonts/public-sans-latin-500-normal.woff2",
  "/assets/fonts/public-sans-latin-600-normal.woff2",
  "/assets/fonts/public-sans-latin-800-normal.woff2",
  "/assets/icon.svg",
  "/assets/icons/apple-touch-icon.png",
  "/assets/icons/icon-192.png",
  "/assets/icons/icon-512.png",
  "/assets/icons/maskable-512.png",
  "/assets/labs.js",
  "/assets/pages.js",
  "/assets/style.css",
  "/assets/theme.js",
  "/ccna/",
  "/cissp/",
  "/cysa-plus/",
  "/data/catalog.js",
  "/data/ccna.js",
  "/data/cissp.js",
  "/data/cysa-plus.js",
  "/data/isc2-cc.js",
  "/data/lab-map.js",
  "/data/labs-blueteam.js",
  "/data/labs-foundations.js",
  "/data/labs-grc.js",
  "/data/labs-network.js",
  "/data/network-plus.js",
  "/data/security-plus.js",
  "/data/sscp.js",
  "/isc2-cc/",
  "/manifest.webmanifest",
  "/network-plus/",
  "/security-plus/",
  "/sscp/"
];

self.addEventListener("install", e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(PRECACHE)));
});
self.addEventListener("activate", e => {
  e.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(k => k.startsWith("certhub-") && k !== CACHE).map(k => caches.delete(k)))).then(() => self.clients.claim()));
});
self.addEventListener("message", e => { if (e.data === "skip-waiting") self.skipWaiting(); });
self.addEventListener("fetch", e => {
  const req = e.request;
  const url = new URL(req.url);
  if (req.method !== "GET" || url.origin !== location.origin) return;
  if (req.mode === "navigate") {
    // Pages: network first so updates show immediately; cached copy when offline.
    e.respondWith(fetch(req).then(res => { const copy = res.clone(); caches.open(CACHE).then(c => c.put(req, copy)); return res; })
      .catch(() => caches.match(req).then(r => r || caches.match(url.pathname.endsWith("/") ? url.pathname : url.pathname + "/")).then(r => r || caches.match("/404.html"))));
    return;
  }
  // Scripts, styles, data, fonts: cache first; this version's cache is filled at install.
  e.respondWith(caches.match(req).then(r => r || fetch(req).then(res => {
    if (res.ok) { const copy = res.clone(); caches.open(CACHE).then(c => c.put(req, copy)); }
    return res;
  })));
});
