/* Generated by tools/build.js. Lets the site work offline and picks up new questions
   automatically. The version changes whenever any page, script, style or data file changes. */
const VERSION = "0a364a05c112";
const CACHE = "certhub-" + VERSION;
const VM_CACHE = "studytocert-vm-df4453ff3908";
const VM_FILES = ["/vendor/vm/config.json","/vendor/vm/libv86.js","/vendor/vm/seabios.bin","/vendor/vm/state.bin.zst","/vendor/vm/v86.wasm","/vendor/vm/vgabios.bin","/vendor/vm/xterm.css","/vendor/vm/xterm.js"];
const PRECACHE = [
  "/",
  "/404.html",
  "/a-plus-core1/",
  "/a-plus-core2/",
  "/ai-102/",
  "/ai-200/",
  "/ai-900/",
  "/assets/achieve.js?v=5b3e68e8a9b4",
  "/assets/app.js?v=136140245dbb",
  "/assets/awscli.js",
  "/assets/azcli.js",
  "/assets/blueteam.js",
  "/assets/careers.js?v=08130a86d20c",
  "/assets/core.js?v=a96d026dd629",
  "/assets/engine.js?v=c55a050adbe4",
  "/assets/examday.js?v=2fc4eee6014d",
  "/assets/fonts/public-sans-latin-400-normal.woff2",
  "/assets/fonts/public-sans-latin-500-normal.woff2",
  "/assets/fonts/public-sans-latin-600-normal.woff2",
  "/assets/fonts/public-sans-latin-800-normal.woff2",
  "/assets/frameworks.js?v=54b4d504e8d0",
  "/assets/fw.js",
  "/assets/fx.js?v=5c98d500159f",
  "/assets/games.js",
  "/assets/habits.js?v=cd69319fdf06",
  "/assets/icon.svg",
  "/assets/icons/apple-touch-icon.png",
  "/assets/icons/icon-192.png",
  "/assets/icons/icon-512.png",
  "/assets/icons/maskable-512.png",
  "/assets/ios.js",
  "/assets/kql.js",
  "/assets/kube.js",
  "/assets/labs.js?v=5cfd5f045d89",
  "/assets/native.js",
  "/assets/netdesign.js",
  "/assets/pages.js?v=aeb366bcf59d",
  "/assets/pcap.js",
  "/assets/pro.js?v=ebe02d201f83",
  "/assets/pwsh.js",
  "/assets/py-worker.mjs",
  "/assets/review.js?v=6548a0e07051",
  "/assets/shell.js",
  "/assets/style.css?v=748d3f5642c8",
  "/assets/support.js",
  "/assets/sync.js?v=b6e8cc3b2238",
  "/assets/tf.js",
  "/assets/theme.js?v=a52affcb5efa",
  "/assets/tutor.js",
  "/assets/vm.js",
  "/aws-cloud-practitioner/",
  "/aws-developer/",
  "/aws-saa/",
  "/aws-security/",
  "/az-104/",
  "/az-802/",
  "/az-900/",
  "/ccna/",
  "/ccnp-encor/",
  "/ccsp/",
  "/ccst-networking/",
  "/cisa/",
  "/cism/",
  "/cissp/",
  "/cka/",
  "/ckad/",
  "/cloud-plus/",
  "/cwna/",
  "/cysa-plus/",
  "/data-plus/",
  "/data/careers.js",
  "/data/catalog.js?v=e0d398ddd874",
  "/data/compare.js",
  "/data/dayinlife.js",
  "/data/diagrams.js",
  "/data/frameworks.js?v=8f24c97a452d",
  "/data/gen/a-plus-core1-plan.js",
  "/data/gen/a-plus-core1.js?v=b59551ec8bfd",
  "/data/gen/a-plus-core2-plan.js",
  "/data/gen/a-plus-core2.js?v=6207440fe354",
  "/data/gen/ai-102-plan.js",
  "/data/gen/ai-102.js?v=44a31b6d9ae5",
  "/data/gen/ai-200-plan.js",
  "/data/gen/ai-200.js?v=adb76dd9e699",
  "/data/gen/ai-900-plan.js",
  "/data/gen/ai-900.js?v=b15b77542829",
  "/data/gen/aws-cloud-practitioner-plan.js",
  "/data/gen/aws-cloud-practitioner.js?v=010c835da98d",
  "/data/gen/aws-developer-plan.js",
  "/data/gen/aws-developer.js?v=d0fc2e43deb3",
  "/data/gen/aws-saa-plan.js",
  "/data/gen/aws-saa.js?v=f49fdfe06cf0",
  "/data/gen/aws-security-plan.js",
  "/data/gen/aws-security.js?v=b89b90f9a315",
  "/data/gen/az-104-plan.js",
  "/data/gen/az-104.js?v=537977bab16e",
  "/data/gen/az-802-plan.js",
  "/data/gen/az-802.js?v=b01740cc31df",
  "/data/gen/az-900-plan.js",
  "/data/gen/az-900.js?v=6f6dd0a102e5",
  "/data/gen/ccna-plan.js",
  "/data/gen/ccna.js?v=74c70a5bba94",
  "/data/gen/ccnp-encor-plan.js",
  "/data/gen/ccnp-encor.js?v=61b00f922fd9",
  "/data/gen/ccsp-plan.js",
  "/data/gen/ccsp.js?v=7738ab39f01a",
  "/data/gen/ccst-networking-plan.js",
  "/data/gen/ccst-networking.js?v=2db26260859a",
  "/data/gen/cisa-plan.js",
  "/data/gen/cisa.js?v=918532bdc4ca",
  "/data/gen/cism-plan.js",
  "/data/gen/cism.js?v=9e42fb8dd828",
  "/data/gen/cissp-plan.js",
  "/data/gen/cissp.js?v=b7c93d794482",
  "/data/gen/cka-plan.js",
  "/data/gen/cka.js?v=c6469049c5e6",
  "/data/gen/ckad-plan.js",
  "/data/gen/ckad.js?v=4d57079400b0",
  "/data/gen/cloud-plus-plan.js",
  "/data/gen/cloud-plus.js?v=b7aca5363b5b",
  "/data/gen/cwna-plan.js",
  "/data/gen/cwna.js?v=0030fc1b374f",
  "/data/gen/cysa-plus-plan.js",
  "/data/gen/cysa-plus.js?v=ad676c3d9694",
  "/data/gen/data-plus-plan.js",
  "/data/gen/data-plus.js?v=5c642895015b",
  "/data/gen/fortinet-fortigate-plan.js",
  "/data/gen/fortinet-fortigate.js?v=b5f08ca4d912",
  "/data/gen/google-ace-plan.js",
  "/data/gen/google-ace.js?v=57f14e9b8203",
  "/data/gen/google-cdl-plan.js",
  "/data/gen/google-cdl.js?v=ee5b0e102e50",
  "/data/gen/isc2-cc-plan.js",
  "/data/gen/isc2-cc.js?v=d10cec38ae44",
  "/data/gen/java-se-plan.js",
  "/data/gen/java-se.js?v=529cd384e9e2",
  "/data/gen/jncia-junos-plan.js",
  "/data/gen/jncia-junos.js?v=63a7ddc36541",
  "/data/gen/linux-plus-plan.js",
  "/data/gen/linux-plus.js?v=194d12c70426",
  "/data/gen/network-plus-plan.js",
  "/data/gen/network-plus.js?v=4e986c73efcd",
  "/data/gen/palo-alto-ngfw-plan.js",
  "/data/gen/palo-alto-ngfw.js?v=8d7327bf42ad",
  "/data/gen/pcap-plan.js",
  "/data/gen/pcap.js?v=65caa3536b2f",
  "/data/gen/pcep-plan.js",
  "/data/gen/pcep.js?v=9a655cd9e854",
  "/data/gen/project-plus-plan.js",
  "/data/gen/project-plus.js?v=bcff1f2b854a",
  "/data/gen/rhcsa-plan.js",
  "/data/gen/rhcsa.js?v=efa38f2d9154",
  "/data/gen/sc-200-plan.js",
  "/data/gen/sc-200.js?v=03777d35dae0",
  "/data/gen/sc-300-plan.js",
  "/data/gen/sc-300.js?v=475375bda11c",
  "/data/gen/sc-500-plan.js",
  "/data/gen/sc-500.js?v=8219f5118025",
  "/data/gen/security-plus-plan.js",
  "/data/gen/security-plus.js?v=7c137a54847f",
  "/data/gen/securityx-plan.js",
  "/data/gen/securityx.js?v=cdff0be20f03",
  "/data/gen/server-plus-plan.js",
  "/data/gen/server-plus.js?v=236d0d8e2407",
  "/data/gen/sscp-plan.js",
  "/data/gen/sscp.js?v=fef0af63b3f2",
  "/data/gen/terraform-plan.js",
  "/data/gen/terraform.js?v=955792b379ea",
  "/data/help.js",
  "/data/jobmarket.js",
  "/data/lab-index.js?v=b04073378268",
  "/data/lab-map.js?v=f32f96d63ff3",
  "/data/labs-blueteam.js",
  "/data/labs-cloud.js",
  "/data/labs-data-ai.js",
  "/data/labs-foundations.js",
  "/data/labs-grc.js",
  "/data/labs-more.js",
  "/data/labs-neteng.js",
  "/data/labs-network.js",
  "/data/labs-secadmin.js",
  "/data/labs-software.js",
  "/data/labs-sysadmin.js",
  "/data/news.js?v=1c8042196b4e",
  "/data/site.js?v=594083be672c",
  "/data/videos.js?v=6ab09cfea04f",
  "/data/vmlabs.js",
  "/fortinet-fortigate/",
  "/google-ace/",
  "/google-cdl/",
  "/isc2-cc/",
  "/java-se/",
  "/jncia-junos/",
  "/linux-plus/",
  "/manifest.webmanifest",
  "/network-plus/",
  "/palo-alto-ngfw/",
  "/pcap/",
  "/pcep/",
  "/project-plus/",
  "/rhcsa/",
  "/sc-200/",
  "/sc-300/",
  "/sc-500/",
  "/security-plus/",
  "/securityx/",
  "/server-plus/",
  "/sscp/",
  "/terraform/"
];

self.addEventListener("install", e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(PRECACHE)));
});
self.addEventListener("activate", e => {
  e.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(k => (k.startsWith("certhub-") && k !== CACHE) || (k.startsWith("studytocert-vm-") && k !== VM_CACHE)).map(k => caches.delete(k)))).then(() => self.clients.claim()));
});
self.addEventListener("message", e => {
  if (e.data === "skip-waiting") self.skipWaiting();
  // "Use the VM offline": download the practice VM's files into their own cache now.
  if (e.data && e.data.type === "cache-vm") {
    const reply = ok => e.ports && e.ports[0] && e.ports[0].postMessage({ ok });
    const base = new URL("./", location.href).pathname.replace(/[/]$/, "");
    const get = (c, f) => c.match(base + f).then(hit => hit || fetch(base + f).then(r => (r.ok ? c.put(base + f, r) : Promise.reject(new Error(f)))));
    e.waitUntil(caches.open(VM_CACHE).then(c => Promise.all(VM_FILES.map(f => get(c, f)))).then(() => reply(true), () => reply(false)));
  }
  // "Save for offline": the page asks for its lessons, questions and simulations to be cached now.
  if (e.data && e.data.type === "cache-urls" && Array.isArray(e.data.urls)) {
    const urls = e.data.urls.filter(u => { try { return new URL(u, location.href).origin === location.origin; } catch (x) { return false; } });
    const reply = ok => e.ports && e.ports[0] && e.ports[0].postMessage({ ok });
    e.waitUntil(caches.open(CACHE).then(c => Promise.all(urls.map(u => fetch(u).then(r => r.ok ? c.put(u, r) : Promise.reject(new Error(u)))))).then(() => reply(true), () => reply(false)));
  }
});
self.addEventListener("fetch", e => {
  const req = e.request;
  const url = new URL(req.url);
  if (req.method !== "GET" || url.origin !== location.origin) return;
  if (req.mode === "navigate") {
    // Pages: network first so updates show immediately; cached copy when offline.
    e.respondWith(fetch(req).then(res => { const copy = res.clone(); caches.open(CACHE).then(c => c.put(req, copy)); return res; })
      .catch(() => caches.match(req).then(r => r || caches.match(url.pathname.endsWith("/") ? url.pathname : url.pathname + "/")).then(r => r || caches.match("/404.html"))));
    return;
  }
  // Practice VM files: their own long-lived cache (see VM_CACHE).
  if (url.pathname.includes("/vendor/vm/")) {
    e.respondWith(caches.open(VM_CACHE).then(c => c.match(req).then(r => r || fetch(req).then(res => { if (res.ok && res.status === 200) c.put(req, res.clone()); return res; }))));
    return;
  }
  // Scripts, styles, data, fonts: cache first; this version's cache is filled at install.
  e.respondWith(caches.match(req).then(r => r || fetch(req).then(res => {
    if (res.ok) { const copy = res.clone(); caches.open(CACHE).then(c => c.put(req, copy)); }
    return res;
  })));
});
