/* Generated by tools/build.js. Lets the site work offline and picks up new questions
   automatically. The version changes whenever any page, script, style or data file changes. */
const VERSION = "6f5a58ac39f6";
const CACHE = "certhub-" + VERSION;
const PRECACHE = [
  "/",
  "/404.html",
  "/a-plus-core1/",
  "/a-plus-core2/",
  "/ai-102/",
  "/ai-200/",
  "/ai-900/",
  "/assets/app.js",
  "/assets/awscli.js",
  "/assets/azcli.js",
  "/assets/careers.js",
  "/assets/core.js",
  "/assets/engine.js",
  "/assets/examday.js",
  "/assets/fonts/public-sans-latin-400-normal.woff2",
  "/assets/fonts/public-sans-latin-500-normal.woff2",
  "/assets/fonts/public-sans-latin-600-normal.woff2",
  "/assets/fonts/public-sans-latin-800-normal.woff2",
  "/assets/frameworks.js",
  "/assets/fw.js",
  "/assets/icon.svg",
  "/assets/icons/apple-touch-icon.png",
  "/assets/icons/icon-192.png",
  "/assets/icons/icon-512.png",
  "/assets/icons/maskable-512.png",
  "/assets/ios.js",
  "/assets/kql.js",
  "/assets/kube.js",
  "/assets/labs.js",
  "/assets/pages.js",
  "/assets/pcap.js",
  "/assets/pro.js",
  "/assets/pwsh.js",
  "/assets/py-worker.mjs",
  "/assets/shell.js",
  "/assets/style.css",
  "/assets/sync.js",
  "/assets/tf.js",
  "/assets/theme.js",
  "/aws-cloud-practitioner/",
  "/aws-developer/",
  "/aws-saa/",
  "/az-104/",
  "/az-802/",
  "/az-900/",
  "/ccna/",
  "/ccnp-encor/",
  "/ccst-networking/",
  "/cissp/",
  "/cka/",
  "/ckad/",
  "/cloud-plus/",
  "/cwna/",
  "/cysa-plus/",
  "/data-plus/",
  "/data/careers.js",
  "/data/catalog.js",
  "/data/diagrams.js",
  "/data/frameworks.js",
  "/data/gen/a-plus-core1.js",
  "/data/gen/a-plus-core2.js",
  "/data/gen/ai-102.js",
  "/data/gen/ai-200.js",
  "/data/gen/ai-900.js",
  "/data/gen/aws-cloud-practitioner.js",
  "/data/gen/aws-developer.js",
  "/data/gen/aws-saa.js",
  "/data/gen/az-104.js",
  "/data/gen/az-802.js",
  "/data/gen/az-900.js",
  "/data/gen/ccna.js",
  "/data/gen/ccnp-encor.js",
  "/data/gen/ccst-networking.js",
  "/data/gen/cissp.js",
  "/data/gen/cka.js",
  "/data/gen/ckad.js",
  "/data/gen/cloud-plus.js",
  "/data/gen/cwna.js",
  "/data/gen/cysa-plus.js",
  "/data/gen/data-plus.js",
  "/data/gen/fortinet-fortigate.js",
  "/data/gen/google-ace.js",
  "/data/gen/google-cdl.js",
  "/data/gen/isc2-cc.js",
  "/data/gen/java-se.js",
  "/data/gen/jncia-junos.js",
  "/data/gen/linux-plus.js",
  "/data/gen/network-plus.js",
  "/data/gen/palo-alto-ngfw.js",
  "/data/gen/pcap.js",
  "/data/gen/pcep.js",
  "/data/gen/project-plus.js",
  "/data/gen/rhcsa.js",
  "/data/gen/sc-200.js",
  "/data/gen/sc-300.js",
  "/data/gen/sc-500.js",
  "/data/gen/security-plus.js",
  "/data/gen/securityx.js",
  "/data/gen/server-plus.js",
  "/data/gen/sscp.js",
  "/data/gen/terraform.js",
  "/data/lab-map.js",
  "/data/labs-blueteam.js",
  "/data/labs-cloud.js",
  "/data/labs-data-ai.js",
  "/data/labs-foundations.js",
  "/data/labs-grc.js",
  "/data/labs-more.js",
  "/data/labs-neteng.js",
  "/data/labs-network.js",
  "/data/labs-secadmin.js",
  "/data/labs-software.js",
  "/data/labs-sysadmin.js",
  "/data/site.js",
  "/fortinet-fortigate/",
  "/google-ace/",
  "/google-cdl/",
  "/isc2-cc/",
  "/java-se/",
  "/jncia-junos/",
  "/linux-plus/",
  "/manifest.webmanifest",
  "/network-plus/",
  "/palo-alto-ngfw/",
  "/pcap/",
  "/pcep/",
  "/project-plus/",
  "/rhcsa/",
  "/sc-200/",
  "/sc-300/",
  "/sc-500/",
  "/security-plus/",
  "/securityx/",
  "/server-plus/",
  "/sscp/",
  "/terraform/"
];

self.addEventListener("install", e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(PRECACHE)));
});
self.addEventListener("activate", e => {
  e.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(k => k.startsWith("certhub-") && k !== CACHE).map(k => caches.delete(k)))).then(() => self.clients.claim()));
});
self.addEventListener("message", e => {
  if (e.data === "skip-waiting") self.skipWaiting();
  // "Save for offline": the page asks for its lessons, questions and simulations to be cached now.
  if (e.data && e.data.type === "cache-urls" && Array.isArray(e.data.urls)) {
    const urls = e.data.urls.filter(u => { try { return new URL(u, location.href).origin === location.origin; } catch (x) { return false; } });
    const reply = ok => e.ports && e.ports[0] && e.ports[0].postMessage({ ok });
    e.waitUntil(caches.open(CACHE).then(c => Promise.all(urls.map(u => fetch(u).then(r => r.ok ? c.put(u, r) : Promise.reject(new Error(u)))))).then(() => reply(true), () => reply(false)));
  }
});
self.addEventListener("fetch", e => {
  const req = e.request;
  const url = new URL(req.url);
  if (req.method !== "GET" || url.origin !== location.origin) return;
  if (req.mode === "navigate") {
    // Pages: network first so updates show immediately; cached copy when offline.
    e.respondWith(fetch(req).then(res => { const copy = res.clone(); caches.open(CACHE).then(c => c.put(req, copy)); return res; })
      .catch(() => caches.match(req).then(r => r || caches.match(url.pathname.endsWith("/") ? url.pathname : url.pathname + "/")).then(r => r || caches.match("/404.html"))));
    return;
  }
  // Scripts, styles, data, fonts: cache first; this version's cache is filled at install.
  e.respondWith(caches.match(req).then(r => r || fetch(req).then(res => {
    if (res.ok) { const copy = res.clone(); caches.open(CACHE).then(c => c.put(req, copy)); }
    return res;
  })));
});
